name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Stiahnutie kódu
      uses: actions/checkout@v4

    - name: Nastavenie Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        # Dočasne sme vypli 'cache: gradle', pretože pri vnorenej štruktúre 
        # priečinkov to robí presne tú chybu, ktorú vidíš na screenshote.

    - name: Udelenie práv na spustenie pre Gradle Wrapper
      run: chmod +x ./gradlew
      working-directory: ./android # <--- Hľadáme v podpriečinku android

    - name: Vygenerovanie Debug APK
      run: ./gradlew assembleDebug
      working-directory: ./android # <--- Spúšťame v podpriečinku android

    - name: Uloženie APK do artefaktov
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        # Musíme upraviť aj cestu, odkiaľ sa má APK na konci stiahnuť
        path: android/app/build/outputs/apk/debug/app-debug.apk
